<a href="https://colab.research.google.com/github/aryan-chettri/aryan-chettri/blob/main/fundamentals_of_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a pytorch code


In [1]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
Tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [4]:
Tensor.ndim

3

In [5]:
Tensor.shape


torch.Size([3, 2, 3])

In [6]:
Tensor[2
       ]

tensor([[13, 14, 15],
        [16, 17, 18]])

In [7]:
random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.9640, 0.5470, 0.2373, 0.8189],
        [0.1551, 0.4124, 0.8830, 0.5381],
        [0.3294, 0.7446, 0.9671, 0.3907]])

In [8]:
random_tensors.shape


torch.Size([3, 4])

In [9]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
ones = torch.ones(size=(3,4))
ones
ones.dtype
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
### Creating a range of tensors

In [12]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
torch.arange(start = 1, end = 100 , step = 10)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [14]:
ten_zeroes = torch.zeros_like(torch.arange(start = 1 , end = 10))
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
float_32_tensor = torch.tensor([3., 6., 9.], dtype = None, device = "cpu")


In [16]:
float_16 = float_32_tensor.type(torch.float16)
float_16


tensor([3., 6., 9.], dtype=torch.float16)

In [17]:
float_16 * float_32_tensor

tensor([ 9., 36., 81.])

In [18]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [19]:
# Create a tensor

some_tensor = torch.rand(3,4)

rand_tensor = some_tensor*100

In [20]:

print(some_tensor)
print(f"Datatype of tensor :{some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")

print(f"Device tensor is on :{some_tensor.device}")

tensor([[0.7595, 0.8470, 0.6631, 0.4648],
        [0.4711, 0.3282, 0.1403, 0.4828],
        [0.5855, 0.3906, 0.8808, 0.4091]])
Datatype of tensor :torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x7a2a6d2e49a0>
Device tensor is on :cpu


# Manipulating tensors

Tensor operations include

Addition

substaction

multiplication

division

matrix multiplication

In [21]:
tensor = torch.tensor([1,2,3])

tensor + 10

tensor * 10

tensor / 10


tensor([0.1000, 0.2000, 0.3000])

In [22]:
import torch

tensor = torch.tensor([1,2,3])

tensor * tensor

tensor([1, 4, 9])

In [23]:
torch.matmul(tensor, tensor)

tensor(14)

In [24]:
%%time

value = 0 ;

for i in range (len(tensor)):

  value = value + tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.26 ms, sys: 79 µs, total: 1.34 ms
Wall time: 1.66 ms


In [25]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 44 µs, sys: 7 µs, total: 51 µs
Wall time: 55.3 µs


tensor(14)

In [26]:
(torch.matmul(torch.rand(3,100), torch.rand(100,3))*100).shape

torch.Size([3, 3])

In [27]:
# Shapes for matrix multiplication

import torch

tensor_A = torch.rand(3,2)

tensor_B = torch.rand(3,2)

torch.matmul(tensor_A, tensor_B.T).shape

tensor_B.T

tensor([[0.9627, 0.9069, 0.0738],
        [0.3486, 0.3950, 0.4700]])

In [28]:
## Finding the min, max, mean, sum, etc (tensor aggregation)

x = torch.arange(0,100,10)

x

x.dtype

torch.int64

In [29]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [30]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [31]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [32]:
# finding the sum

torch.sum(x)

#finding the positional min and max

x.argmin(), x.argmax()

(tensor(0), tensor(9))

## reshaping , stacking, squeezing and unsqueezing tensors

reshaping = reshapes an input tensor to a defined shape

view teturn a view of an input tensor of certain shape but keeps the same as the orginal one

In [33]:
x= torch.arange(1. , 10.)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [34]:
x_reshaped = x.reshape(1, 9)

x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [35]:
z = x.view(1, 9)

z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
z[:, 0] = 5

z , x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [37]:
#Stacking tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim = 1)

x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [38]:
#torch. squeez

x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [39]:
y = x_reshaped.squeeze()

y.shape, x_reshaped.shape

(torch.Size([9]), torch.Size([1, 9]))

In [40]:
y = y.unsqueeze(dim =1)

y

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [41]:
# torch.unsqueeze

In [42]:
#torch. permute changes the size of the size of the tensor in a specified order

x=torch.rand(2,3,5)

torch.permute(x, (2, 0, 1)).size()

x_original = torch.rand(size=(224, 224, 3))

x_permuted = torch.permute(x_original , (2, 0, 1))

print(f"The orginal tensor is {x_original.shape}")

print(f"The permuted tensor is {x_permuted.shape}")


The orginal tensor is torch.Size([224, 224, 3])
The permuted tensor is torch.Size([3, 224, 224])


In [43]:
x_original[0, 0, 0] = 2345

x_original[0, 0, 0] , x_permuted[0, 0, 0]

(tensor(2345.), tensor(2345.))

from torch.return_types import nanmedian
## indexing selectiondata from tensors


indesing with pytorch is similar dto indexing with numpy

In [44]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)

x, x.shape



(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [45]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [46]:
## Pytorch tensors and numpy

